New adoc Template; Added allowed-licenses.txt; Improved README.md…
deviceinsight/dependency-license-exporter pull request #3
Opened 2020-10-09 09:35 UTC by d-huynh

* New adoc Template with four columns
* Added an allowed licenses list
* Improved README.md
* Update license merge and license override lists

2020-10-13 15:08 UTC, mwalser requested changes
Hi @d-huynh,

thank you for your PR. I have added some comments with minor suggestions.

Also, i think we should get rid of the code duplication in the two FreeMarker files. I don't have any FreeMarker experience, but it seems like there is a [<#include> directive](https://freemarker.apache.org/docs/ref_directive_include.html) that could be used for this.

2020-10-13 15:08 UTC, mwalser commented on README.md
> +							<includedLicenses>classpath:allowed-licenses.txt</includedLicenses>
The code around is indented via spaces. Please also convert this indentation to spaces

2020-10-13 15:08 UTC, mwalser commented on src/main/resources/allowed-licenses.txt
> +GPL-2.0
I don't think we allow GPL v2/v3 within our projects. Please sync this list with http://deviceinsight.pages.device-insight.de/project-development-guidelines/open-source-dependencies/

2020-10-13 15:08 UTC, mwalser commented on src/main/resources/com/deviceinsight/license/exporter/adoc-template-four-columns.ftl
> +</#function>
Up to this line everything is shared with the adoc-template.ftl file. Is there a possibility to create a common file for this?

2020-10-13 15:08 UTC, mwalser commented on src/main/resources/com/deviceinsight/license/exporter/adoc-template-four-columns.ftl
> +<#-- spdxIdentifiers should contain all identifiers that are merged in license-merges.txt -->
I'm not really happy with the name of the file `adoc-template-four-columns.ftl` since the other template also has four columns.

Maybe `adoc-template-with-link.ftl`? Argh. Naming things is hard

2020-10-19 15:20 UTC, d-huynh commented on src/main/resources/allowed-licenses.txt
> +GPL-2.0
Integrated the list into the allowed-list file

2020-10-19 15:21 UTC, d-huynh commented on src/main/resources/com/deviceinsight/license/exporter/adoc-template-four-columns.ftl
> +<#-- spdxIdentifiers should contain all identifiers that are merged in license-merges.txt -->
`adoc-template-with-human-readable-lib-names.ftl` is long, but safe, don't you think? :-D

2020-10-19 15:22 UTC, d-huynh commented on README.md
> +							<includedLicenses>classpath:allowed-licenses.txt</includedLicenses>
I saw the difference in length and changed, but didn't know they were spaces. Changed now.

2020-10-19 15:52 UTC, d-huynh commented on src/main/resources/com/deviceinsight/license/exporter/adoc-template-four-columns.ftl
> +</#function>
Done

2020-10-19 15:54 UTC, mwalser commented on src/main/resources/com/deviceinsight/license/exporter/adoc-template-four-columns.ftl
> +<#-- spdxIdentifiers should contain all identifiers that are merged in license-merges.txt -->
Sounds good

2020-10-28 08:47 UTC, merged

2020-11-02 21:44 UTC, d-huynh commented on src/main/resources/allowed-licenses.txt
> +GPL-2.0
Note: Janino's license is confirmed to be BSD-3-Clause [here](https://github.com/janino-compiler/janino/issues/136).